openapi: 3.0.0
info:
  title: DX Cluster REST API
  description: REST API for real-time amateur radio DX cluster spot data
  version: 1.0.0
  contact:
    name: DX Cluster API Support
    url: https://github.com/stevebuer/cs330-projects
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080/api
    description: Local development server
  - url: https://dx.jxqz.org/api
    description: Production server

paths:
  /health:
    get:
      summary: Health check
      description: Returns the health status of the API and database connection
      operationId: getHealth
      tags:
        - System
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy, unhealthy]
                  database:
                    type: string
                    enum: [connected, disconnected]
        '500':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /:
    get:
      summary: API information
      description: Returns API metadata and available endpoints
      operationId: getApiInfo
      tags:
        - System
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  version:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
                  endpoints:
                    type: object

  /stats:
    get:
      summary: Database statistics
      description: Returns comprehensive database statistics including totals and recent activity
      operationId: getStats
      tags:
        - Statistics
      responses:
        '200':
          description: Database statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  total:
                    $ref: '#/components/schemas/TotalStats'
                  today:
                    $ref: '#/components/schemas/TodayStats'
                  recent:
                    $ref: '#/components/schemas/RecentStats'

  /spots:
    get:
      summary: Get DX spots
      description: Returns DX spots with optional filtering and pagination
      operationId: getSpots
      tags:
        - Spots
      parameters:
        - name: limit
          in: query
          description: Maximum number of spots to return
          schema:
            type: integer
            minimum: 1
            maximum: 500
            default: 50
        - name: offset
          in: query
          description: Number of spots to skip for pagination
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: band
          in: query
          description: Filter by amateur radio band
          schema:
            type: string
            enum: [10m, 12m, 15m, 17m, 20m, 30m, 40m, 80m, 160m]
        - name: min_freq
          in: query
          description: Minimum frequency in kHz
          schema:
            type: number
            format: float
        - name: max_freq
          in: query
          description: Maximum frequency in kHz
          schema:
            type: number
            format: float
        - name: dx_call
          in: query
          description: Filter by DX station callsign
          schema:
            type: string
        - name: spotter_call
          in: query
          description: Filter by spotter callsign
          schema:
            type: string
        - name: mode
          in: query
          description: Filter by operating mode
          schema:
            type: string
            enum: [CW, SSB, FT8, FT4, PSK31, RTTY, AM, FM]
        - name: since
          in: query
          description: Minimum spot time (ISO datetime)
          schema:
            type: string
            format: date-time
        - name: until
          in: query
          description: Maximum spot time (ISO datetime)
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of DX spots
          content:
            application/json:
              schema:
                type: object
                properties:
                  spots:
                    type: array
                    items:
                      $ref: '#/components/schemas/Spot'
                  count:
                    type: integer
                  total_available:
                    type: integer
                  filters_applied:
                    type: object
                  timestamp:
                    type: string
                    format: date-time
        '400':
          description: Invalid parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /spots/recent:
    get:
      summary: Get recent spots
      description: Returns the most recent DX spots from the last 24 hours
      operationId: getRecentSpots
      tags:
        - Spots
      parameters:
        - name: limit
          in: query
          description: Maximum number of spots to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: hours
          in: query
          description: Hours to look back
          schema:
            type: integer
            minimum: 1
            maximum: 168
            default: 24
      responses:
        '200':
          description: Recent DX spots
          content:
            application/json:
              schema:
                type: object
                properties:
                  spots:
                    type: array
                    items:
                      $ref: '#/components/schemas/Spot'
                  count:
                    type: integer
                  hours:
                    type: integer
                  timestamp:
                    type: string
                    format: date-time

  /bands:
    get:
      summary: Get band information
      description: Returns activity statistics for all amateur radio bands
      operationId: getBands
      tags:
        - Bands
      responses:
        '200':
          description: Band activity statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  bands:
                    type: array
                    items:
                      $ref: '#/components/schemas/Band'
                  timestamp:
                    type: string
                    format: date-time

  /frequency/histogram:
    get:
      summary: Get frequency histogram
      description: Returns frequency distribution data for creating histograms
      operationId: getFrequencyHistogram
      tags:
        - Analytics
      parameters:
        - name: bins
          in: query
          description: Number of histogram bins
          schema:
            type: integer
            minimum: 10
            maximum: 200
            default: 50
        - name: band
          in: query
          description: Filter by specific band
          schema:
            type: string
        - name: hours
          in: query
          description: Hours to look back
          schema:
            type: integer
            minimum: 1
            maximum: 168
            default: 24
      responses:
        '200':
          description: Frequency histogram data
          content:
            application/json:
              schema:
                type: object
                properties:
                  histogram:
                    type: array
                    items:
                      $ref: '#/components/schemas/HistogramBin'
                  band:
                    type: string
                  total_spots:
                    type: integer
                  bins:
                    type: integer
                  timestamp:
                    type: string
                    format: date-time

  /activity/hourly:
    get:
      summary: Get hourly activity
      description: Returns spot activity broken down by hour of the day
      operationId: getHourlyActivity
      tags:
        - Analytics
      parameters:
        - name: hours
          in: query
          description: Hours of historical data to analyze
          schema:
            type: integer
            minimum: 1
            maximum: 168
            default: 24
        - name: timezone
          in: query
          description: Timezone for hour calculation
          schema:
            type: string
            default: UTC
      responses:
        '200':
          description: Hourly activity data
          content:
            application/json:
              schema:
                type: object
                properties:
                  hourly_activity:
                    type: array
                    items:
                      $ref: '#/components/schemas/HourlyActivity'
                  hours_analyzed:
                    type: integer
                  timezone:
                    type: string
                  timestamp:
                    type: string
                    format: date-time

  /callsigns/top:
    get:
      summary: Get top callsigns
      description: Returns the most active DX stations and spotters
      operationId: getTopCallsigns
      tags:
        - Callsigns
      parameters:
        - name: limit
          in: query
          description: Number of callsigns to return for each category
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
        - name: hours
          in: query
          description: Hours to look back
          schema:
            type: integer
            minimum: 1
            maximum: 168
            default: 24
      responses:
        '200':
          description: Top active callsigns
          content:
            application/json:
              schema:
                type: object
                properties:
                  top_spotted:
                    type: array
                    items:
                      $ref: '#/components/schemas/TopSpotted'
                  top_spotters:
                    type: array
                    items:
                      $ref: '#/components/schemas/TopSpotter'
                  timestamp:
                    type: string
                    format: date-time

components:
  schemas:
    Spot:
      type: object
      properties:
        id:
          type: integer
          description: Unique spot identifier
        timestamp:
          type: string
          format: date-time
          description: When the spot was created
        dx_call:
          type: string
          description: Callsign of the DX station
        frequency:
          type: string
          description: Operating frequency in kHz
        spotter_call:
          type: string
          description: Callsign of the spotter
        comment:
          type: string
          nullable: true
          description: Additional information
        mode:
          type: string
          nullable: true
          description: Operating mode
        signal_report:
          type: string
          nullable: true
          description: Signal strength report
        grid_square:
          type: string
          nullable: true
          description: Maidenhead grid square
        band:
          type: string
          description: Amateur radio band

    Band:
      type: object
      properties:
        band:
          type: string
          description: Band designation
        spot_count:
          type: integer
          description: Total spots in this band
        dx_stations:
          type: integer
          description: Unique DX stations spotted
        min_freq:
          type: string
          description: Lowest frequency spotted (kHz)
        max_freq:
          type: string
          description: Highest frequency spotted (kHz)
        latest_spot:
          type: string
          format: date-time
          description: Most recent spot timestamp

    TotalStats:
      type: object
      properties:
        total_spots:
          type: integer
        unique_dx_stations:
          type: integer
        unique_spotters:
          type: integer
        earliest_spot:
          type: string
          format: date-time
        latest_spot:
          type: string
          format: date-time

    TodayStats:
      type: object
      properties:
        spots_today:
          type: integer
        dx_stations_today:
          type: integer
        spotters_today:
          type: integer

    RecentStats:
      type: object
      properties:
        spots_last_hour:
          type: integer
        active_spotters:
          type: integer

    HistogramBin:
      type: object
      properties:
        frequency_range:
          type: string
          description: Frequency range for this bin
        count:
          type: integer
          description: Number of spots in this bin
        center_freq:
          type: number
          format: float
          description: Center frequency of the bin

    HourlyActivity:
      type: object
      properties:
        hour:
          type: integer
          description: Hour of day (0-23)
        spot_count:
          type: integer
          description: Number of spots in this hour
        unique_dx:
          type: integer
          description: Unique DX stations spotted
        unique_spotters:
          type: integer
          description: Unique spotters active

    TopSpotted:
      type: object
      properties:
        callsign:
          type: string
          description: DX station callsign
        times_spotted:
          type: integer
          description: Number of times spotted
        spotted_by:
          type: integer
          description: Number of unique spotters
        last_spotted:
          type: string
          format: date-time
          description: Most recent spot time

    TopSpotter:
      type: object
      properties:
        callsign:
          type: string
          description: Spotter callsign
        spot_count:
          type: integer
          description: Number of spots made
        stations_spotted:
          type: integer
          description: Number of unique stations spotted
        last_activity:
          type: string
          format: date-time
          description: Most recent activity

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error type
        message:
          type: string
          description: Detailed error message

tags:
  - name: System
    description: System health and API information
  - name: Spots
    description: DX spot data retrieval
  - name: Bands
    description: Amateur radio band information
  - name: Analytics
    description: Data analysis and statistics
  - name: Callsigns
    description: Callsign activity and rankings
  - name: Statistics
    description: Database and activity statistics